MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeadsExtraNorm"
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    NORM: "SyncBN"
#    NORM: "BN"
TEST:
  PRECISE_BN:
    ENABLED: True
#    ENABLED: False
SOLVER:
  IMS_PER_BATCH: 1
#  BASE_LR: 0.02
  BASE_LR: 0.00025
