_BASE_: "Base-RCNN-C4-BN.yaml"
MODEL:
  MASK_ON: False
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "downstream/object_detection/byol_pricetag_detector.pkl"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("price_labels_train",)
  TEST: ("price_labels_val",)
SOLVER:
  STEPS: (120000, 160000)
#  MAX_ITER: 180000
  MAX_ITER: 180000
